from flask import Blueprint, jsonify
import random
from app.models import SensorData

api = Blueprint("api", __name__)

# --- API Endpoints ---

@api.route("/status", methods=["GET"])
def get_status():
    """
    A simple endpoint to confirm the backend is running.
    """
    from .services.get_status import get_status_data
    initial_data = get_status_data()
    return jsonify(initial_data)

@api.route("/recommendation", methods=["GET"])
def get_recommendation():
    """
    Returns the recommendation generated by the recommendation service.
    """
    # from .services.get_recommendation import get_recommendation_data
    # recommendation = get_recommendation_data()
    recommendation = { "message": "Move your plant into the shade" }
    return jsonify(recommendation)

@api.route("/data", methods=["GET"])
def get_sensor_data():
    """Generate randomized plant sensor data and send it to the frontend."""
    data = SensorData(name="PLANT")

    # randomized but bounded values
    data.set_air_temp(value=round(random.uniform(60, 80), 1), max_val=80, min_val=60)
    data.set_water_temp(value=round(random.uniform(60, 72), 1), max_val=72, min_val=60)
    data.set_humidity(value=round(random.uniform(0.4, 0.6), 2), max_val=0.6, min_val=0.4)
    data.set_electrical_conductivity(value=round(random.uniform(0.8, 2.2), 1), max_val=2.2, min_val=0.8)
    data.set_pH(value=round(random.uniform(5.5, 7.0), 2), max_val=7.0, min_val=5.5)

    return jsonify(data.create_dict()), 200
